package view;

import java.util.ArrayList;
import java.util.List;
import logic.Car;
import view.strategies.DeleteCarStrategy;

/**
 *
 * @author Marci
 */
public class CarDeleteForm extends javax.swing.JDialog {

    private Car car;
    private List<CarEventListener> listeners;
    private CarHandlingStrategy strategy;

    /**
     * Creates new form DeleteSecureForm
     *
     * @param parent
     * @param c
     */
    public CarDeleteForm(java.awt.Frame parent, Car c) {
        super(parent, false);
        this.car = c;
        listeners = new ArrayList<>();
        strategy = new DeleteCarStrategy();
        initComponents();
    }

    public void addCarEventListener(CarEventListener l) {
        listeners.add(l);
    }

    public void removeCarEventListener(CarEventListener l) {
        listeners.remove(l);
    }

    private void notifyListeners() {
        for (CarEventListener listener : listeners) {
            strategy.notify(car, listener);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfTypeDelete = new javax.swing.JLabel();
        btDeleteOk = new javax.swing.JButton();
        btCancel = new javax.swing.JButton();
        tfDelete = new javax.swing.JTextField();
        tfDeleteQuestion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setFocusCycleRoot(false);
        setLocationByPlatform(true);
        setPreferredSize(new java.awt.Dimension(400, 200));
        setResizable(false);

        tfTypeDelete.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tfTypeDelete.setText("Type \"DELETE\" into the field to confirm.");
        tfTypeDelete.setAlignmentY(0.0F);
        tfTypeDelete.setAutoscrolls(true);

        btDeleteOk.setText("OK");
        btDeleteOk.setEnabled(false);
        btDeleteOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteOkActionPerformed(evt);
            }
        });

        btCancel.setText("Cancel");
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });

        tfDelete.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfDeleteKeyReleased(evt);
            }
        });

        tfDeleteQuestion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfDeleteQuestion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tfDeleteQuestion.setText("Do you want to delete this car?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfTypeDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfDeleteQuestion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btDeleteOk)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btCancel))
                            .addComponent(tfDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(tfDeleteQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfTypeDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btDeleteOk)
                    .addComponent(btCancel))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btDeleteOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteOkActionPerformed
        notifyListeners();
        strategy.save(car);
        this.dispose();
    }//GEN-LAST:event_btDeleteOkActionPerformed

    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btCancelActionPerformed

    private void tfDeleteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfDeleteKeyReleased
        String tfInput = tfDelete.getText().
                toLowerCase();
        if (tfInput.equals("delete")) {
            btDeleteOk.setEnabled(true);
        } else {
            btDeleteOk.setEnabled(false);
        }
    }//GEN-LAST:event_tfDeleteKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancel;
    private javax.swing.JButton btDeleteOk;
    private javax.swing.JTextField tfDelete;
    private javax.swing.JLabel tfDeleteQuestion;
    private javax.swing.JLabel tfTypeDelete;
    // End of variables declaration//GEN-END:variables
}
