package view;

import java.awt.Frame;
import java.util.ArrayList;
import java.util.List;
import logic.Car;
import utils.StringFormatter;

/**
 *
 * @author Marci
 */
public class CarEditorForm extends javax.swing.JDialog {

    private Car car;
    private List<CarEventListener> listeners;
    private CarHandlingStrategy strategy;

    /**
     * Creates new form CarHandlerForm
     *
     * @param parent
     * @param newId
     */
    public CarEditorForm(java.awt.Frame parent, long newId) {
        super(parent, true);
        initComponents();
        listeners = new ArrayList<>();
        car = new Car();
        car.setId(newId);

    }

    public CarEditorForm(Frame frame, Car car) {
        this(frame, car.getId());
        this.car = car;
        fillFormFromCar();
    }

    public void setCarHandlingStrategy(CarHandlingStrategy strategy) {
        this.strategy = strategy;
    }

    public void addCarEventListener(CarEventListener l) {
        listeners.add(l);
    }

    public void removecarEventListener(CarEventListener l) {
        listeners.remove(l);
    }

    private void notifyListeners() {
        for (CarEventListener listener : listeners) {
            strategy.notify(car, listener);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfBrand = new javax.swing.JTextField();
        tfModel = new javax.swing.JTextField();
        tfEngineSize = new javax.swing.JTextField();
        lbBrand = new javax.swing.JLabel();
        lbModel = new javax.swing.JLabel();
        lbEngineSize = new javax.swing.JLabel();
        btSave = new javax.swing.JButton();
        btCancel = new javax.swing.JButton();
        lbLicencePlate = new javax.swing.JLabel();
        tfLicencePlate = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setLocationByPlatform(true);
        setResizable(false);

        lbBrand.setText("Brand");

        lbModel.setText("Model");

        lbEngineSize.setText("Engine size");

        btSave.setText("Save");
        btSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveActionPerformed(evt);
            }
        });

        btCancel.setText("Cancel");
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });

        lbLicencePlate.setText("Licence plate");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbBrand, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbModel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbEngineSize, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                            .addComponent(lbLicencePlate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfModel, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfEngineSize, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfLicencePlate, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btCancel)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbLicencePlate)
                    .addComponent(tfLicencePlate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbBrand)
                    .addComponent(tfBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbModel)
                    .addComponent(tfModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEngineSize)
                    .addComponent(tfEngineSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSave)
                    .addComponent(btCancel))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveActionPerformed
        fillcarWithFormData();
        strategy.save(car);
        notifyListeners();
        this.dispose();
    }//GEN-LAST:event_btSaveActionPerformed

    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btCancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancel;
    private javax.swing.JButton btSave;
    private javax.swing.JLabel lbBrand;
    private javax.swing.JLabel lbEngineSize;
    private javax.swing.JLabel lbLicencePlate;
    private javax.swing.JLabel lbModel;
    private javax.swing.JTextField tfBrand;
    private javax.swing.JTextField tfEngineSize;
    private javax.swing.JTextField tfLicencePlate;
    private javax.swing.JTextField tfModel;
    // End of variables declaration//GEN-END:variables

    private void fillcarWithFormData() {
        car.setLicencePlate(tfLicencePlate.getText().
                toUpperCase());
        car.setBrand(StringFormatter.firstCharUpperRestLower(tfBrand.getText()));
        car.setModel(StringFormatter.firstCharUpperRestLower(tfModel.getText()));
        car.setEngineSize(Integer.parseInt(tfEngineSize.getText()));
    }

    private void fillFormFromCar() {
        tfLicencePlate.setText(car.getLicencePlate());
        tfBrand.setText(car.getBrand());
        tfModel.setText(car.getModel());
        tfEngineSize.setText(String.valueOf(car.getEngineSize()));
        tfLicencePlate.requestFocus();
        tfLicencePlate.selectAll();
    }

}
